### ISSUE TITLE
Fix these drones. 

### ISSUE THREAD

**Issue by Xandaron539** [Garmundo/Extended-unit-arsenal#4]
Shield, tarflyer, hawk, nebula, hephaestus don't work. Aquarius don't deal any damage. Kugelblitz and tremor are too weak.
If thorium crawler work, then it is really slow and weak.

**Comment by Garmundo** [comment]
Hi! Thanks for the comment, I added some buffs to the units you mentioned. 
I tried them out and they all seem to work.

What I think the problem was:
I forgot to put the status effect for the liuids

For nebula, cryo and tar (but mostly for nebula) they have a short range
And are more focused on being used in attack where they swoop in into enemy
Structures, they usually won't attack units unless they are close.

Hephaestus is a bomber like the ghoul but the bombs stay for a while when it
Doesn't hit a building, also more focised on being used in attack

Aquarius' main feature is its long range and freezing ability
Having a coiple can infa stall capitals and your other units or turrets
Can grind them in place, they just have a bit of damage unlike the cryoflyer

Thorium crawlers can deal a pretty obscene amount of damage, it can
Wipe out a flock of revenants, however, you should add in some cover for it
It has hp like a revenant but when the enemy defense is strong it will die.

The kugelblitz tbh still needs a bit of testing, it works great with flocks of small enemies especially when you have a bunch of them, it deals little damage but to alot of units by splash damage and will usually wipe out units simultaneously. But it becomes very obsolete against capitals and walls.

The tremor is yet another attack centered unit, great at blasting walls and stationary targets, against moving ones though, not so much. Try using a bunch of them in sandbox, they will obliterate walls.

I might need to learn scripting for the shield drone. So that might take a while.

If there are more issues let me know

**Comment by ThatOneBepis** [comment]
for lightning-based units, i have noticed they only tend to attack a specific unit **once**. Is this supposed to be intentional on mindustry's end or what

**Comment by Garmundo** [comment]
It's likely in mindustry's code. I just make .json files which create new code for blocks and units using the built-in code system mindustry has. I can't really wrap my head around scripting yet.

**Comment by ThatOneBepis** [comment]
good to know. Probably it will work better when scripts are added in
